# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    container_name: tqs_lab7_p3_db
    restart: always
    environment:
      POSTGRES_PASSWORD: postgre
      POSTGRES_USER: postgre
      POSTGRES_DB: postgre
