pipeline {
    agent any
    tools {
        jdk 'Corretto-11.0.9.12.1'
        maven 'Apache Maven 3.6.3'
    }
    stages {
        stage('Install') {
            steps {
                sh 'mvn clean install'
            }
            post {
                always {
                    junit '**/target/*-reports/TEST-*.xml'
                }
            }
        }
    }
}
