pipeline {
    agent any
    tools {
        jdk 'Corretto-11.0.9.12.1'
        maven 'Apache Maven 3.6.3'
    }
    stages {
        stage('test java installation') {
            steps {
                sh 'java -version'
            }
        }
        stage('test maven installation') {
            steps {
                sh 'mvn -version'
            }
        }
    }
}
