// Generated by Selenium IDE
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.AfterEach;
import static org.junit.jupiter.api.Assertions.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;




import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class P2_export {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @BeforeEach
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
    driver.get("https://blazedemo.com/");
    driver.manage().window().setSize(new Dimension(1440, 875));
  }
  @AfterEach
  public void tearDown() {
    driver.quit();
  }
  
  /*@Test
  public void testedeExportao() {
    driver.get("https://blazedemo.com/");
    driver.manage().window().setSize(new Dimension(1440, 875));
    driver.findElement(By.name("fromPort")).click();
    
    {
      WebElement dropdown = driver.findElement(By.name("fromPort"));
      dropdown.findElement(By.xpath("//option[. = 'Portland']")).click();
    }
    
    driver.findElement(By.name("toPort")).click();
    
    {
      WebElement dropdown = driver.findElement(By.name("toPort"));
      dropdown.findElement(By.xpath("//option[. = 'Berlin']")).click();
    }
    
    driver.findElement(By.cssSelector(".btn-primary")).click();
    
    driver.findElement(By.cssSelector("tr:nth-child(2) .btn")).click();
    
    driver.findElement(By.id("inputName")).click();
    
    driver.findElement(By.id("inputName")).sendKeys("Andre");
    
    driver.findElement(By.id("address")).click();
    
    driver.findElement(By.id("address")).sendKeys("rua");
    
    driver.findElement(By.id("city")).click();
    
    driver.findElement(By.id("city")).sendKeys("cidade");
    
    driver.findElement(By.id("state")).click();
    
    driver.findElement(By.id("state")).sendKeys("estado");
    
    driver.findElement(By.id("zipCode")).click();
    
    driver.findElement(By.id("zipCode")).sendKeys("codigopostal");
    
    driver.findElement(By.id("cardType")).click();
    
    {
      WebElement dropdown = driver.findElement(By.id("cardType"));
      dropdown.findElement(By.xpath("//option[. = 'American Express']")).click();
    }
    
    driver.findElement(By.id("creditCardNumber")).click();
    
    driver.findElement(By.id("creditCardNumber")).sendKeys("12345678");
    
    driver.findElement(By.id("nameOnCard")).click();
    
    driver.findElement(By.id("nameOnCard")).sendKeys("Andre M.");
    
    driver.findElement(By.cssSelector(".checkbox")).click();
    
    driver.findElement(By.cssSelector(".btn-primary")).click();
  }*/

  @Test
  public void refactored(){
    BlazeDemo home = new BlazeDemo(driver);
    home.setFrom("Portland");
    home.setTo("Berlin");

    BlazeDemoReserve reserva = home.clickFindFlights();

    BlazeDemoPurchase purchase = reserva.clickChooseThisFlight();
    purchase.setName("Andre");
    purchase.setAddress("rua");
    purchase.setCity("cidade");
    purchase.setState("estado");
    purchase.setZipCode("codigopostal");
    purchase.setCardType("amex");
    purchase.setCreditCardNumber("12345678");
    purchase.setNameOnCard("Andre M.");
    purchase.clickCheckbox();
    
    BlazeDemoConfirmation confirmacao = purchase.clickConfirm();
    
    
    driver.findElement(By.id("address")).click();
    
    driver.findElement(By.id("address")).sendKeys("rua");
    
    driver.findElement(By.id("city")).click();
    
    driver.findElement(By.id("city")).sendKeys("cidade");
    
    driver.findElement(By.id("state")).click();
    
    driver.findElement(By.id("state")).sendKeys("estado");
    
    driver.findElement(By.id("zipCode")).click();
    
    driver.findElement(By.id("zipCode")).sendKeys("codigopostal");
    
    driver.findElement(By.id("cardType")).click();
    
    {
      WebElement dropdown = driver.findElement(By.id("cardType"));
      dropdown.findElement(By.xpath("//option[. = 'American Express']")).click();
    }
    
    driver.findElement(By.id("creditCardNumber")).click();
    
    driver.findElement(By.id("creditCardNumber")).sendKeys("12345678");
    
    driver.findElement(By.id("nameOnCard")).click();
    
    driver.findElement(By.id("nameOnCard")).sendKeys("Andre M.");
    
    driver.findElement(By.cssSelector(".checkbox")).click();
    
    driver.findElement(By.cssSelector(".btn-primary")).click();
  }
}
