version: '3.3'

services:
  db:
    image: mysql
    #restart: always
    environment:
      MYSQL_DATABASE: 'ies'
      MYSQL_USER: 'demo'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_PASSWORD: 'root'
    ports:
      - '3306:3306'
    #volumes:
      #- db-data1:/var/lib/mysql
      #- ./mysql.sql:/docker-entrypoint-initdb.d/mysql.sql
    #expose:
    # opens port 3306 on the container
    #- '3306'

  
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    #volumes:
    #  - ./rabbitmq/etc/definitions.json:/etc/rabbitmq/definitions.json
    #  - ./rabbitmq/etc/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    #  - ./rabbitmq/data:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit
    #  - ./rabbitmq/logs:/var/log/rabbitmq/log
    ports:
      - '5672:5672'
      - '15672:15672'

  backend:
    build:
      context: my-smArt-home
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
      - rabbitmq
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/ies
      SPRING_DATASOURCE_USERNAME: demo
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_RABBITMQ_HOST: rabbitmq
    restart: on-failure

  #sensing:
  #  build:
  #    context: broker
  #    dockerfile: Dockerfile
  #  depends_on:
  #    - db
  #    - rabbitmq
  #    - backend
  #  environment:
  #    RABBITMQ_IP: rabbitmq
  #    SERVER_IP: backend
  #  #restart: on-failure

  client:
    build:
      context: web_site
      dockerfile: Dockerfile
    ports:
      - '80:80'
    depends_on:
      - db
      - rabbitmq
      #- sensing
    volumes:
      - ./src:/etc/share/nginx/html
    environment: 
      SERVER_IP: backend

  #nginx:
  #  image: nginx:latest
  #  volumes:
  #    - ./nginx.conf:/etc/nginx/nginx.conf
  #    - ./web_site:/usr/share/nginx/html
  #  ports:
  #    - 8081:8081
  #  depends_on:
  #    - db
  #    - rabbitmq

volumes:
  db-data1: # names our volume
