// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TestedeExportaoTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testedeExportao() {
    // Test name: Teste de Exportação
    // Step # | name | target | value | comment
    // 1 | open | / |  | 
    driver.get("https://blazedemo.com/");
    // 2 | setWindowSize | 1440x875 |  | 
    driver.manage().window().setSize(new Dimension(1440, 875));
    // 3 | click | name=fromPort |  | 
    driver.findElement(By.name("fromPort")).click();
    // 4 | select | name=fromPort | label=Portland | 
    {
      WebElement dropdown = driver.findElement(By.name("fromPort"));
      dropdown.findElement(By.xpath("//option[. = 'Portland']")).click();
    }
    // 5 | click | name=toPort |  | 
    driver.findElement(By.name("toPort")).click();
    // 6 | select | name=toPort | label=Berlin | 
    {
      WebElement dropdown = driver.findElement(By.name("toPort"));
      dropdown.findElement(By.xpath("//option[. = 'Berlin']")).click();
    }
    // 7 | click | css=.btn-primary |  | 
    driver.findElement(By.cssSelector(".btn-primary")).click();
    // 8 | click | css=tr:nth-child(2) .btn |  | 
    driver.findElement(By.cssSelector("tr:nth-child(2) .btn")).click();
    // 9 | click | id=inputName |  | 
    driver.findElement(By.id("inputName")).click();
    // 10 | type | id=inputName | Andre | 
    driver.findElement(By.id("inputName")).sendKeys("Andre");
    // 11 | click | id=address |  | 
    driver.findElement(By.id("address")).click();
    // 12 | type | id=address | rua | 
    driver.findElement(By.id("address")).sendKeys("rua");
    // 13 | click | id=city |  | 
    driver.findElement(By.id("city")).click();
    // 14 | type | id=city | cidade | 
    driver.findElement(By.id("city")).sendKeys("cidade");
    // 15 | click | id=state |  | 
    driver.findElement(By.id("state")).click();
    // 16 | type | id=state | estado | 
    driver.findElement(By.id("state")).sendKeys("estado");
    // 17 | click | id=zipCode |  | 
    driver.findElement(By.id("zipCode")).click();
    // 18 | type | id=zipCode | codigopostal | 
    driver.findElement(By.id("zipCode")).sendKeys("codigopostal");
    // 19 | click | id=cardType |  | 
    driver.findElement(By.id("cardType")).click();
    // 20 | select | id=cardType | label=American Express | 
    {
      WebElement dropdown = driver.findElement(By.id("cardType"));
      dropdown.findElement(By.xpath("//option[. = 'American Express']")).click();
    }
    // 21 | click | id=creditCardNumber |  | 
    driver.findElement(By.id("creditCardNumber")).click();
    // 22 | type | id=creditCardNumber | 12345678 | 
    driver.findElement(By.id("creditCardNumber")).sendKeys("12345678");
    // 23 | click | id=nameOnCard |  | 
    driver.findElement(By.id("nameOnCard")).click();
    // 24 | type | id=nameOnCard | Andre M. | 
    driver.findElement(By.id("nameOnCard")).sendKeys("Andre M.");
    // 25 | click | css=.checkbox |  | 
    driver.findElement(By.cssSelector(".checkbox")).click();
    // 26 | click | css=.btn-primary |  | 
    driver.findElement(By.cssSelector(".btn-primary")).click();
  }
}
